language: ruby
rvm:
  - 2.0.0
  - 2.1.0
before_script:
  - cd spec/dummy
  - RAILS_ENV=test bundle exec rake db:migrate
  - RAILS_ENV=test bundle exec rails s &
  - cd ../..
script: ./travis.sh
notifications:
  email: false
  webhooks: 
    secure: "ZY0D/J9Qcs2GSrVTZf4j+IxWKeQ9D2WXmPkPCRgfT4zU97S2oSQzYhTd1o17puxZn9OeCQOzSog+0Btr4A0x8vMIyonB07QJaoAaHJIKFKhV4Qj11nc3dSnv6XWkBKuTRTR9OWQDPHQmYL3XbEIyzqOc4NmVeXu3Z2p1M4US3AA="